services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - AES_MASTER_KEY=0246ea6bae10761cbc1540130902b4eafe380eaf4c33a5e9ece0964d96ba48ca
      - BOT_TOKEN=8225216134:AAGZK21DRQjM4Y1439DbYqU1BgXt5Kalr1s
      - DB_HOST=db
      - DB_NAME=hotels
      - DB_USER=root
      - DB_PASS=yourpassword
      - DB_PORT=3306
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: hotels
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: arm64v8/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=yourpassword
    depends_on:
      - db

volumes:
  db_data:
